buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
siteStream:
  id: site
  entityId: site-152836
  fields:
    - name
    - logo
    - favicon
    - header
    - footer
    - twitterHandle
    - facebookPageUrl
    - instagramHandle
    - linkedInUrl
    - pinterestUrl
    - tikTokUrl
    - youTubeChannelUrl
    - copyrightMessage
  localization:
    locales:
      - en
livePreviewConfiguration:
  setupCommand: ":"
# authentication:
#   policyName: auth-policy
#   includePaths:
#     - /edit